### ISSUE TITLE
Organização dos pacotes

### ISSUE THREAD

**Issue by daruan-rst** [ThaliaLira/game-of-thrones-api#1]
Boa noite, querida!

Tudo bem contigo?

Percebi que o package de repository está dentro de domain / entity

O correto seria que estivessem no mesmo nível da controller, correto?

As duas interfaces de repository estão devendo uma anotação de componente.

Por fim, dentro de controller, acho que os DTOs poderiam ser Records. Quer praticar o uso de Records para esse projeto?

**Comment by ThaliaLira** [comment]
Oi Daru!

- Modificação da estrutura dos repositórios realizada
- Devido os repositories serem herdados das interfaces do Spring Data JPA (JpaRepository), não é preciso anotar com o @Component, porque o Spring tem uma configuração que automaticamente faz o scan de quem herda de tais interfaces.
- Como combinamos, irei prosseguir com os DTOs da forma como estão e utilizá-los como Record posteriormente para irmos evoluindo o aprendizado. 

Obrigada pelos apontamentos <3
